#
# (C) Copyright 2019
#  Jack Lee
#


#INCL  += -I$(CONFIG_M500768)/rtl8307h_sdk/include/asicdrv/basic


obj-y	+= rtk_api.o
# obj-y	+= rtk_i2c.o
obj-y	+= rtk_error.o

obj-y	+= rtl8307h_asicdrv_port.o
obj-y	+= rtl8307h_asicdrv_phy.o

obj-y	+= rtl8307h_reg_list.o
obj-y	+= rtl8307h_regField_list.o
obj-y	+= rtl8307h_table_list.o
obj-y	+= rtl8307h_tableField_list.o
obj-y	+= rtl8307h_asicdrv_mib.o

