#
# (C) Copyright 2019
#  Jack Lee
#


#INCL  += -I$(CONFIG_M500768)/rtl8307h_sdk/include/asicdrv/basic


obj-$(CONFIG_MUX7XX)	+= rtk_api.o
obj-$(CONFIG_MUX7XX)	+= rtk_i2c.o
obj-$(CONFIG_MUX7XX)	+= rtk_error.o

obj-$(CONFIG_MUX7XX)	+= rtl8307h_asicdrv_port.o
obj-$(CONFIG_MUX7XX)	+= rtl8307h_asicdrv_phy.o

obj-$(CONFIG_MUX7XX)	+= rtl8307h_reg_list.o
obj-$(CONFIG_MUX7XX)	+= rtl8307h_regField_list.o
obj-$(CONFIG_MUX7XX)	+= rtl8307h_table_list.o
obj-$(CONFIG_MUX7XX)	+= rtl8307h_tableField_list.o
obj-$(CONFIG_MUX7XX)	+= rtl8307h_asicdrv_mib.o

