
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/basic/rtl8307h_reg_list.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/basic/rtl8307h_regField_list.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/basic/rtl8307h_table_list.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/basic/rtl8307h_tableField_list.o

