#
# Makefile for the contributed drivers
#
MUXLAB_SRC:=$(TOPDIR)/mux

INCL  += -I$(MUXLAB_SRC)/

COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/muxHwInit.o
COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/muxHwFpga.o
COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/muxHwUtils.o
COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/muxHwSi5351b.o

#COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/pwmc/pwmc.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/sii1136/sii1136.o


# INCL  += -I$(MUXLAB_SRC)/adv7619
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/LIB
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/HAL
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/HAL/5G
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/HAL/5G/ADV7619
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/HAL/5G/ADV7619/HAL
# INCL  += -I$(MUXLAB_SRC)/adv7619/RX/HAL/5G/ADV7619/MACROS

# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/wrapper.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_afe_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_cp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_hdmi_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_sdp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_sdp_vdp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/rx_vdp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/rx_5g_cp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/rx_5g_gen_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/rx_5g_hdmi_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/rx_5g_no_supp_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/ADV7619/HAL/7619_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/HAL/5G/ADV7619/HAL/7619_ini_hal.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_afe.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_cdec.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_cec.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_cp.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_dpp_csc.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_gen.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_hdmi.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_isr.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_multi.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_sdp.o
# COBJS-$(CONFIG_TWI0)		+= $(MUXLAB_SRC)/adv7619/RX/LIB/rx_vdp.o
