<?php

namespace App\Controllers;

/**
 * @SWG\Swagger(
 *   schemes={"http"},
 *   host="device_ip:8888",
 *   basePath="/",
 *   @SWG\Info(
 *     title="500762 HDMI Digital Signage Media Player Api Documentation",
 *     version="1.0.0"
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="401_response",
 *   @SWG\Property(
 *      property="status",
 *      type="string",
 *      example="failed"
 *   ),
 *   @SWG\Property(
 *      property="data",
 *      type="array",
 *      @SWG\Items()
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="system",
 *   @SWG\Property(
 *      property="model",
 *      type="string",
 *      example="500774"
 *   ),
 *   @SWG\Property(
 *      property="product",
 *      type="string",
 *      example="HdmiOverIP-774"
 *   ),
 *   @SWG\Property(
 *      property="name",
 *      type="string",
 *      example="HdmiOverIP-774"
 *   ),
 *   @SWG\Property(
 *      property="ver",
 *      type="string",
 *      example="1.0.0"
 *   ),
 *   @SWG\Property(
 *      property="built",
 *      type="string",
 *      example="Aug 22 2019 17:45:41"
 *   ),
 *   @SWG\Property(
 *      property="isTx",
 *      type="integer",
 *      description="1 for TX, 0 for RX",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="ip",
 *      type="string",
 *      example="192.168.168.100"
 *   ),
 *   @SWG\Property(
 *      property="mask",
 *      type="string",
 *      example="255.255.255.0"
 *   ),
 *   @SWG\Property(
 *      property="gateway",
 *      type="string",
 *      example="192.168.168.1"
 *   ),
 *   @SWG\Property(
 *      property="mac",
 *      type="string",
 *      example="FC:C2:3D:0D:16:13"
 *   ),
 *   @SWG\Property(
 *      property="isDhcp",
 *      type="integer",
 *      example=1
 *   ),
 *   @SWG\Property(
 *      property="isDipOn",
 *      type="integer",
 *      example=1
 *   ),
 *   @SWG\Property(
 *      property="reset",
 *      type="integer",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="reboot",
 *      type="integer",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="blinkLed",
 *      type="integer",
 *      example=0
 *   ),
 * )
 */

/**
 * @SWG\Definition(
 *   definition="video",
 *   @SWG\Items(
 *        @SWG\Property(
 *          property="ip",
 *          type="string",
 *          example="192.168.168.100"
 *        ),
 *        @SWG\Property(
 *          property="port",
 *          type="integer",
 *          example=36000
 *        ),
 *        @SWG\Property(
 *          property="sdp",
 *          type="string",
 *          example="sdp"
 *        ),
 *        @SWG\Property(
 *          property="height",
 *          type="integer",
 *          example=1080
 *        ),
 *        @SWG\Property(
 *          property="width",
 *          type="integer",
 *          example=1920
 *        ),
 *        @SWG\Property(
 *          property="fps",
 *          type="string",
 *          example="60"
 *        ),
 *        @SWG\Property(
 *          property="colorSpace",
 *          type="string",
 *          example="YCbCr-4:2:2"
 *        ),
 *        @SWG\Property(
 *          property="depth",
 *          type="integer",
 *          example=16
 *        ),
 *        @SWG\Property(
 *         property="payloadType",
 *          type="integer",
 *          example=96
 *        ),
 *        @SWG\Property(
 *          property="intlce",
 *          type="integer",
 *          example=1
 *       )
 *   ) 
 * )
 */

/**
 * @SWG\Definition(
 *   definition="audio",
 *   @SWG\Items(   
 *   @SWG\Property(
 *      property="ip",
 *      type="string",
 *      example="192.168.168.100"
 *   ),
 *   @SWG\Property(
 *      property="port",
 *      type="integer",
 *      example=36000
 *   ),
 *   @SWG\Property(
 *      property="sdp",
 *      type="string",
 *      example="sdp"
 *   ),
 *   @SWG\Property(
 *      property="sample",
 *      type="string",
 *      example="480000"
 *   ),
 *   @SWG\Property(
 *      property="channels",
 *      type="integer",
 *      example=16
 *   ),
 *   @SWG\Property(
 *      property="depth",
 *      type="integer",
 *      example=16
 *   ),
 *   @SWG\Property(
 *      property="payloadType",
 *      type="integer",
 *      example=96
 *   ),
 *   @SWG\Property(
 *      property="pktSize",
 *      type="string",
 *      example="1ms"
 *   )
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="anc",
 *   @SWG\Items(
 *   @SWG\Property(
 *      property="ip",
 *      type="string",
 *      example="192.168.168.100"
 *   ),
 *   @SWG\Property(
 *      property="port",
 *      type="integer",
 *      example=36000
 *   ),
 *   @SWG\Property(
 *      property="sdp",
 *      type="string",
 *      example="sdp"
 *   ),
 *   @SWG\Property(
 *      property="payloadType",
 *      type="integer",
 *      example=96
 *   ),
 *   @SWG\Property(
 *      property="vpId",
 *      type="integer",
 *      example=132
 *   )
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="sdp",
 *   @SWG\Items(
 *   @SWG\Property(
 *      property="media",
 *      type="string",
 *      example="video"
 *   ),
 *   @SWG\Property(
 *      property="ip",
 *      type="string",
 *      example="192.168.168.100"
 *   ),
 *   @SWG\Property(
 *      property="port",
 *      type="integer",
 *      example=36000
 *   ),
 *   @SWG\Property(
 *      property="uri",
 *      type="string",
 *      example="videoSpd2"
 *   )),
 * )
 */

/**
 * @SWG\Definition(
 *   definition="rs232",
 *   @SWG\Property(
 *      property="baudrate",
 *      type="integer",
 *      example=19200
 *   ),
 *   @SWG\Property(
 *      property="databit",
 *      type="integer",
 *      example=7
 *   ),
 *   @SWG\Property(
 *      property="parity",
 *      type="string",
 *      example="odd"
 *   ),
 *   @SWG\Property(
 *      property="stopbit",
 *      type="integer",
 *      example=2
 *   ),
 *   @SWG\Property(
 *      property="data",
 *      type="string",
 *      example=""
 *   ),
 *   @SWG\Property(
 *      property="isFeedback",
 *      type="integer",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="waitTime",
 *      type="integer",
 *      example=0
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="IR",
 *   @SWG\Property(
 *      property="data",
 *      type="string",
 *      example=""
 *   ),
 *   @SWG\Property(
 *      property="isFeedback",
 *      type="integer",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="waitTime",
 *      type="integer",
 *      example=0
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="security",
 *   @SWG\Property(
 *      property="get_id",
 *      type="string",
 *      example=""
 *   ),
 *   @SWG\Property(
 *      property="get_status",
 *      type="integer",
 *      example=0
 *   ),
 *   @SWG\Property(
 *      property="set_key",
 *      type="string",
 *      example=""
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="rs232List",
 *   @SWG\Property(
 *      property="baudrate",   
 *      @SWG\Items(
 *       type="integer",
 *       example="9600,19200,38400,57600,115200",
 *      )
 *   ),
 *   @SWG\Property(
 *      property="databits",   
 *      @SWG\Items(
 *       type="integer",
 *       example="7,8",
 *      )
 *   ),
 *   @SWG\Property(
 *      property="parity",   
 *      @SWG\Items(
 *       type="string",
 *       example="none,odd,even",
 *      )
 *   ),
 *   @SWG\Property(
 *      property="stopbits",   
 *      @SWG\Items(
 *       type="integer",
 *       example="1,2",
 *      )
 *   ),
 * )
 */

/**
 * @SWG\Definition(
 *   definition="videoList",
 *   @SWG\Property(
 *      property="resolution",
 *      @SWG\Items(
 *       type="string",
 *       example="1920x1080,1280x720",
 *      )
 *   ),
 *   @SWG\Property(
 *      property="colorDepth",
 *      @SWG\Items(
 *       type="integer",
 *       example="8,10,12,16",
 *      )
 *   ),
 *   @SWG\Property(
 *      property="colorSpace",
 *      @SWG\Items(
 *       type="string",
 *       example="YCbCr-4:2:2,YCbCr-4:4:4,RGB",
 *      )
 *   ),
 * )
 */


/**
 * @SWG\Definition(
 *   definition="File",
 *   @SWG\Property(
 *      property="name",
 *      type="string",
 *      example="/media/usb/video.mp4"
 *   ),
 *   @SWG\Property(
 *      property="duration",
 *      type="string",
 *      example="290",
 *      description="in seconds"
 *   )
 * )
 */

/**
 * @SWG\Definition(
 *   definition="Project",
 *              @SWG\Property(
 *                  property="project",
 *                  @SWG\Property(
 *                        property="title",
 *                        type="string",
 *                        example="project1"
 *                 ),
 *                 @SWG\Property(
 *                        property="frames",
 *                        type="array",
 *                        @SWG\Items(
 *                             @SWG\Property(
 *                                  property="weekDay",
 *                                  type="string",
 *                                  example="1",
 *                                  description="0-6 sunday=0"
 *                             ),
 *                             @SWG\Property(
 *                                  property="start",
 *                                  type="string",
 *                                  example="00:00",
 *                                  description="hour(0-23):min(0-59)"
 *                             ),
 *                             @SWG\Property(
 *                                  property="end",
 *                                  type="string",
 *                                  example="07:00",
 *                                  description="hour(0-23):min(0-59)"
 *                             ),
 *                             @SWG\Property(
 *                                  property="windows",
 *                                  description="the screen (layout) is considered always 1080x1920, the windows should fit this measure",
 *                                  type="array",
 *                                  @SWG\Items(
 *                                       @SWG\Property(
 *                                              property="windowId",
 *                                              type="integer",
 *                                              example=1,
 *                                              description="1-5 are visible windows only for video and/or image playlists, window 6 is a hidden one (no size is demanded) just for audio playlist"
 *                                       ),
 *                                       @SWG\Property(
 *                                              property="left",
 *                                              type="integer",
 *                                              example=0,
 *                                              minimum=0,
 *                                              maximum=1840,
 *                                              description="window left position"
 *                                       ),
 *                                       @SWG\Property(
 *                                              property="top",
 *                                              type="integer",
 *                                              example=0,
 *                                              minimum=0,
 *                                              maximum=1000,
 *                                              description="window top position"
 *                                       ),
 *                                       @SWG\Property(
 *                                              property="width",
 *                                              type="integer",
 *                                              example=500,
 *                                              minimum=0,
 *                                              maximum=1920
 *                                       ),
 *                                       @SWG\Property(
 *                                              property="height",
 *                                              type="integer",
 *                                              example=500,
 *                                              minimum=0,
 *                                              maximum=1080
 *                                       ),
 *                                       @SWG\Property(
 *                                              property="playlists",
 *                                              type="array",
 *                                              @SWG\Items(
 *                                                  @SWG\Property(
 *                                                      property="name",
 *                                                      type="string",
 *                                                      example="playlist1",
 *                                                  ),
 *                                                  @SWG\Property(
 *                                                      property="start",
 *                                                      type="string",
 *                                                      example="00:00",
 *                                                      description="hour(0-23):min(0-59)"
 *                                                  ),
 *                                                  @SWG\Property(
 *                                                      property="duration",
 *                                                      type="string",
 *                                                      example="01:30",
 *                                                      description="just used in windows 6 audio playlists"
 *                                                  )
 *                                             )
 *                                       )
 *                                  )
 *                             ),
 *                             @SWG\Property(
 *                                  property="images",
 *                                  type="array",
 *                                  @SWG\Items(
 *                                       @SWG\Property(
 *                                           property="media",
 *                                           type="string",
 *                                           example="/media/usd/index.jpg",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="transparency",
 *                                           type="integer",
 *                                           example=48,
 *                                           description="1-100"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="left",
 *                                           type="integer",
 *                                           example=260,
 *                                           description="1-1920"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="top",
 *                                           type="integer",
 *                                           example=50,
 *                                           description="1-1080"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="width",
 *                                           type="integer",
 *                                           example=1400,
 *                                           description="1-1920"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="height",
 *                                           type="integer",
 *                                           example=220,
 *                                           description="1-1080"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="start",
 *                                           type="string",
 *                                           example="12:00",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="duration",
 *                                           type="string",
 *                                           example="00:05",
 *                                       ),
 *                                  )
 *                             ),
 *                             @SWG\Property(
 *                                  property="texts",
 *                                  type="array",
 *                                  @SWG\Items(
 *                                       @SWG\Property(
 *                                           property="message",
 *                                           type="string",
 *                                           example="message1",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="transparency",
 *                                           type="integer",
 *                                           example=48,
 *                                           description="1-100"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="background",
 *                                           type="string",
 *                                           example="7f7f7f",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="fontColor",
 *                                           type="string",
 *                                           example="ff0600",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="fontSize",
 *                                           type="integer",
 *                                           example=48,
 *                                           description="1-130"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="left",
 *                                           type="integer",
 *                                           example=260,
 *                                           description="1-1920"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="top",
 *                                           type="integer",
 *                                           example=50,
 *                                           description="1-1080"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="width",
 *                                           type="integer",
 *                                           example=1400,
 *                                           description="1-1920"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="height",
 *                                           type="integer",
 *                                           example=220,
 *                                           description="1-1080"
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="start",
 *                                           type="string",
 *                                           example="12:00",
 *                                       ),
 *                                       @SWG\Property(
 *                                           property="duration",
 *                                           type="string",
 *                                           example="00:05",
 *                                       ),
 *                                  )
 *                             ),
 *                             @SWG\Property(
 *                                  property="soundSource",
 *                                  type="integer",
 *                                  example=6,
 *                                  description="1-6, 6 audio hidden window"
 *                             ),
 *                        )
 *                    ),
 *              ),
 * )
 */
class HomeController
{
    public function index($request, $response) {
        return "Home controller";
    }
    
    public function test($request, $response) {
        return "test";
    }
}