include $(TOP)/lib/rtl8305h_sdk/src/asicdrv/Makefile.inc
include $(TOP)/lib/rtl8305h_sdk/src/asicdrv/basic/Makefile.inc

rtl8305h-y += lib/rtl8305h_sdk/src/rtk_i2c.o
rtl8305h-y += lib/rtl8305h_sdk/src/rtk_api.o
rtl8305h-y += lib/rtl8305h_sdk/src/rtk_error.o
rtl8305h-y += lib/rtl8305h_sdk/src/rtk_irom_init.o




