#


include $(RULE_DIR)/Rules.mak

OS		= linux

# 
TYPE=

C_FLAGS += -O2 -Wall \
	-I. -I$(ROOT_DIR)/include \

# CXXFLAGS += -Wall 

ifeq ($(ARCH),arm)
	C_FLAGS += -fPIC 
else
endif

DRIVER_HOME=$(ROOT_DIR)/drivers

CFLAGS_DRIVER=-I$(DRIVER_HOME)/include

