# /bin/sh
# test mamagement message of PTP from local unix socket
# Jack Lee 10.23, 2019

MGMT_MSGS+="CLOCK_DESCRIPTION USER_DESCRIPTION DEFAULT_DATA_SET CURRENT_DATA_SET PARENT_DATA_SET TIME_PROPERTIES_DATA_SET PRIORITY1 PRIORITY2 DOMAIN SLAVE_ONLY CLOCK_ACCURACY "
MGMT_MSGS+="TRACEABILITY_PROPERTIES TIMESCALE_PROPERTIES TIME_STATUS_NP GRANDMASTER_SETTINGS_NP PORT_DATA_SET PORT_DATA_SET_NP LOG_ANNOUNCE_INTERVAL ANNOUNCE_RECEIPT_TIMEOUT "
MGMT_MSGS+="LOG_SYNC_INTERVAL VERSION_NUMBER DELAY_MECHANISM LOG_MIN_PDELAY_REQ_INTERVAL"

MGMT_MSGS="DEFAULT_DATA_SET CURRENT_DATA_SET PARENT_DATA_SET TIME_STATUS_NP PORT_DATA_SET PORT_DATA_SET_NP"

PMC_PROGRAM="./Linux.bin.X86/usr/bin/pmc -u -b 0 "
DOMAIN=2

i=0;

for msg in $MGMT_MSGS; do
		#  0 
		let i+=1;
		cmd="$PMC_PROGRAM 'GET $msg' -d $DOMAIN"
		echo "#$i message $msg $cmd"
		$PMC_PROGRAM "GET $msg" -d $DOMAIN
		echo ""
		echo ""
		
	done
	
