
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_acl.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_dot1x.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_gpio.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_igmp.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_lock.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_lut.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_mem_ctrl.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_mib.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_misc.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_phy.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_port.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_rma.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_svlan.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_vlan.o
rtl8305h-y += lib/rtl8305h_sdk/src/asicdrv/rtl8307h_asicdrv_wol.o

